baseURL: 'https://diogocarapito.com/'
languageCode: 'en-us'
title: "diogo carapito's blog"
theme: "PaperMod"


params:
    homeInfoParams:
        Title: "Hi there "
        Content: "Medical Doctor, Studied @NOVA Medical School, 3rd year General and Family Medicine resident @ARSLVT, Portugal. Postgraduate Program in Information Management and Business Intelligence in Healthcare @NOVA IMS"

    socialIcons:
        - name: "github"
          url: "https://github.com/DiogoCarapito"
        - name: "twitter"
          url: "https://twitter.com/DiogoCarapito"
        - name: "linkedin"
          url: "https://www.linkedin.com/in/diogo-carapito-564a51262/"